ACSETUPSVCPORT=23210
ACSVCPORT=17532
ALLUSERSPROFILE=C:\ProgramData
APPDATA=C:\Users\MR.Laptops\AppData\Roaming
CHROME_CRASHPAD_PIPE_NAME=\\.\pipe\crashpad_12028_DFCRPYWPJXMKCWQB
COMMONPROGRAMFILES=C:\Program Files\Common Files
COMMONPROGRAMFILES(X86)=C:\Program Files (x86)\Common Files
COMMONPROGRAMW6432=C:\Program Files\Common Files
COMPUTERNAME=ALI-ABBU
COMSPEC=C:\Windows\system32\cmd.exe
CONDA_DEFAULT_ENV=base
CONDA_EXE=C:\Users\MR.Laptops\anaconda3\Scripts\conda.exe
CONDA_PREFIX=C:\Users\MR.Laptops\anaconda3
CONDA_PROMPT_MODIFIER=(base) 
CONDA_PYTHON_EXE=C:\Users\MR.Laptops\anaconda3\python.exe
CONDA_ROOT=C:\Users\MR.Laptops\anaconda3
CONDA_SHLVL=1
DRIVERDATA=C:\Windows\System32\Drivers\DriverData
EFC_10032=1
FPS_BROWSER_APP_PROFILE_STRING=Internet Explorer
FPS_BROWSER_USER_PROFILE_STRING=Default
HOMEDRIVE=C:
HOMEPATH=\Users\MR.Laptops
IGCCSVC_DB=AQAAANCMnd8BFdERjHoAwE/Cl+sBAAAACvYkmnjN3kmBiawiM4ANHgQAAAACAAAAAAAQZgAAAAEAACAAAAB4n0Ss+F74CJz/W53IxYI8g3C+JQ54qgnr5GP9vWcjsgAAAAAOgAAAAAIAACAAAAC4aUFF9HDMPB36SMbplos81uyHXll759WKU0w/i6o1OGAAAAAWRgkxy33JFGXJFpNoQeSRZxOkv9Vy8M+GNuJdsyFaPYxv0BCR5UqveqlqGSvoIf+2b3cKIVnSSiOY323Hvhs+J79xmaocBxtdZ+rjM8VtSQ/0pV8DI6TVuL4ZAiw29WpAAAAAuGN4JNGQKAokNb/ntOUmZ72EpB0nIytwQo5gzRgCUSNQOoLA7a6iXcW/SvfNBYE7OWZryZDfCKp8r4Z9o0yaqw==
LOCALAPPDATA=C:\Users\MR.Laptops\AppData\Local
LOGONSERVER=\\ALI-ABBU
NUMBER_OF_PROCESSORS=20
ONEDRIVE=C:\Users\MR.Laptops\OneDrive
ORIGINAL_XDG_CURRENT_DESKTOP=undefined
OS=Windows_NT
PATH=C:\Users\MR.Laptops\AppData\Local\cloud-code\installer\google-cloud-sdk\bin;C:\Users\MR.Laptops\anaconda3;C:\Users\MR.Laptops\anaconda3\Library\mingw-w64\bin;C:\Users\MR.Laptops\anaconda3\Library\usr\bin;C:\Users\MR.Laptops\anaconda3\Library\bin;C:\Users\MR.Laptops\anaconda3\Scripts;C:\Users\MR.Laptops\anaconda3\bin;C:\Users\MR.Laptops\anaconda3\condabin;C:\Users\MR.Laptops\anaconda3;C:\Users\MR.Laptops\anaconda3\Library\mingw-w64\bin;C:\Users\MR.Laptops\anaconda3\Library\usr\bin;C:\Users\MR.Laptops\anaconda3\Library\bin;C:\Users\MR.Laptops\anaconda3\Scripts;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\System32\OpenSSH;C:\Program Files\dotnet;C:\Program Files\nodejs;C:\Program Files\Git\cmd;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Users\MR.Laptops\AppData\Local\Programs\Python\Python313\Scripts;C:\Users\MR.Laptops\AppData\Local\Programs\Python\Python313;C:\Users\MR.Laptops\AppData\Local\Programs\Python\Launcher;C:\Users\MR.Laptops\AppData\Local\Microsoft\WindowsApps;C:\Users\MR.Laptops\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\MR.Laptops\AppData\Roaming\npm;C:\Users\MR.Laptops\AppData\Local\Microsoft\WinGet\Packages\Gyan.FFmpeg_Microsoft.Winget.Source_8wekyb3d8bbwe\ffmpeg-7.1-full_build\bin;.;c:\Users\MR.Laptops\AppData\Roaming\.anaconda\navigator\Code\User\globalStorage\github.copilot-chat\debugCommand
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 183 Stepping 1, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=b701
PROGRAMDATA=C:\ProgramData
PROGRAMFILES=C:\Program Files
PROGRAMFILES(X86)=C:\Program Files (x86)
PROGRAMW6432=C:\Program Files
PROMPT=(base) $P$G
PSMODULEPATH=C:\Users\MR.Laptops\Documents\WindowsPowerShell\Modules;C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules
PUBLIC=C:\Users\Public
RLSSVCPORT=22112
SESSIONNAME=Console
SSL_CERT_FILE=C:\Users\MR.Laptops\anaconda3\Library\ssl\cacert.pem
SYSTEMDRIVE=C:
SYSTEMROOT=C:\Windows
TEMP=C:\Users\MR8F93~1.LAP\AppData\Local\Temp
TMP=C:\Users\MR8F93~1.LAP\AppData\Local\Temp
USERDOMAIN=ALI-ABBU
USERDOMAIN_ROAMINGPROFILE=ALI-ABBU
USERNAME=MR.Laptops
USERPROFILE=C:\Users\MR.Laptops
WINDIR=C:\Windows
ZES_ENABLE_SYSMAN=1
__CONDA_OPENSLL_CERT_FILE_SET="1"
TERM_PROGRAM=vscode
TERM_PROGRAM_VERSION=1.96.4
LANG=en_US.UTF-8
COLORTERM=truecolor
GIT_ASKPASS=c:\Users\MR.Laptops\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\askpass.sh
VSCODE_GIT_ASKPASS_NODE=C:\Users\MR.Laptops\AppData\Local\Programs\Microsoft VS Code\Code.exe
VSCODE_GIT_ASKPASS_EXTRA_ARGS=
VSCODE_GIT_ASKPASS_MAIN=c:\Users\MR.Laptops\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\askpass-main.js
VSCODE_GIT_IPC_HANDLE=\\.\pipe\vscode-git-13bea49b44-sock
CONDA_ALLOW_SOFTLINKS=false
CONDA_EXES="C:\Users\MR.Laptops\anaconda3\Scripts\conda.exe"  
_CONDA_OLD_CHCP=437
VSCODE_INJECTION=1
